### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by bevenky** [adly/blingalytics#2]
Screenshots of this would greatly help in understanding how the structure of sample reports looks like

**Comment by jeffsmohan** [comment]
Agreed! I'm planning on adding some screenshots to the docs, hopefully in the next few days. But this isn't a bug, so I'm closing the issue.

**Comment by jeffsmohan** [comment]
I'd added a screenshot of a very basic example report (the one from the walkthrough, I believe!) to the docs index page. You can see it at blingalytics.rtfd.org. Enjoy!
